export function getNextDecision(decision, action) {
  const base = {
    id: `d_chain_${Date.now()}`,
    status: 'pending',
    subject: decision.subject,
    project: decision.project,
    priority: decision.priority,
    created: 'Just now'
  };

  // Triage -> Specify
  if (decision.decisionType === 'triage' && action === 'Proceed') {
    return {
      ...base,
      decisionType: 'specify',
      question: 'Define spec',
      data: {
        context: `Project [[${decision.project || 'General'}]], Source: ${decision.subject.source}`,
        aiSpec: {
          objective: `Execute: ${decision.subject.title}`,
          format: 'Standard Output',
          constraints: 'None specified'
        },
        successCriteria: [
          { id: 'sc1', text: 'Task completed as requested', checked: false }
        ]
      }
    };
  }

  // Specify -> Verifying
  if (decision.decisionType === 'specify' && action === 'Save & Continue') {
    return {
      ...base,
      decisionType: 'verifying',
      question: 'Verifying output...',
      data: {
        attempt: 1,
        maxAttempts: 3,
        verifier: 'Claude Sonnet',
        criteriaResults: [
          { text: 'Checking completeness...', status: 'pending', note: 'Running...' },
          { text: 'Checking tone...', status: 'pending', note: 'Running...' }
        ]
      }
    };
  }

  // Clarify -> Verifying (Simulated execution)
  if (decision.decisionType === 'clarifying' && action === 'Submit Answers') {
    return {
      ...base,
      decisionType: 'verifying',
      question: 'Executing & Verifying...',
      data: {
        attempt: 1,
        maxAttempts: 3,
        verifier: 'Claude Sonnet',
        criteriaResults: [
          { text: 'User questions answered', status: 'pass', note: 'Included' },
          { text: 'Standard checks', status: 'pass', note: 'Pass' }
        ]
      }
    };
  }

  // Verifying -> Review (Override)
  if (decision.decisionType === 'verifying' && action === 'Override') {
    return {
      ...base,
      decisionType: 'review',
      question: 'Review work (Overridden)',
      data: {
        completedBy: 'Claude (Overridden)',
        verified: false,
        specSummary: { objective: decision.subject.title },
        resultSummary: { preview: '[Draft Content generated by AI...]', fullDocLink: '#' }
      }
    };
  }

  // Review -> Triage (Reject/Restart) or Specify (Revise)
  if (decision.decisionType === 'review' && action === 'Request Changes') {
    return {
      ...base,
      decisionType: 'specify',
      question: 'Refine spec based on feedback',
      data: {
        context: 'Revision requested',
        aiSpec: {
          objective: `Revise: ${decision.subject.title}`,
          feedback: 'Previous attempt rejected.'
        }
      }
    };
  }

  return null;
}
